# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  tags:
    - run
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script: 
    - apt update && apt -y install make autoconf 
  script: 
    - make raiinet
  artifacts:
    paths:
      - raiinet
  # cache outputs to reduce the build time
  cache:
    paths:
      - "*.o"
      - "*.d"

# run tests using the binary built before
# test:
#   stage: test
#   script:
#     - ./runmytests.sh
